language: java
jdk: oraclejdk8
sudo: true

os:
  - linux
addons:
  apt_packages:
    - pandoc

env:
  - ANDROID_HOME=$HOME/android-sdk

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see https://developer.android.com/studio/build/build-cache.html)
    - $HOME/.android/build-cache

install:
  # Download and unzip the Android SDK tools
  # Latest version available here: https://developer.android.com/studio/index.html#downloads
  - wget -q -O $HOME/sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip -qq $HOME/sdk-tools.zip -d $HOME/android-sdk
  - rm $HOME/sdk-tools.zip
  - mkdir -p $ANDROID_HOME/licenses
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
  - mkdir -p $HOME/.android # silence sdkmanager warning
  - echo 'count=0' > $HOME/.android/repositories.cfg # silence sdkmanager warning

  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' 'platform-tools' 'build-tools;27.0.3' > /dev/null
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-27' 'extras;google;m2repository' > /dev/null

#android:
#  components:
#    - tools
#    - platform-tools
#    - tools
#    - build-tools-27.0.3
#    - android-27
#  licenses:
#    - android-sdk-preview-license-.+
#    - android-sdk-license-.+
#    - google-gdk-license-.+

script:
  - ./gradlew clean check --profile
  - pandoc `ls -1rt build/reports/profile/profile-*.html | tail -n1` -t plain
  - ./gradlew dependencyUpdate # I must run this separately due to issues with the support library resolutionStrategy
